import Image from 'next/image';
const outputs=[
 {name:'Shift Drafts',user:'Supervisors',prepare:'Collection, reconciliation, organization, and spreadsheet preparation.',use:'Review exceptions, add operational context, and finalize shift reports.'},
 {name:'Daily Production Reports',user:'Managers',prepare:'Production, molding, labor, quality, plan attainment, and downtime in one consistent view.',use:'Investigate constraints and prioritize staffing, planning, maintenance, or coordination follow-up.'},
 {name:'Weekly Production + Downtime',user:'Managers and teams',prepare:'Comparable performance and downtime evidence across reporting periods.',use:'Identify trends, separate recurring issues from isolated events, and support planning, reviews, and handoffs.'},
];
const controls=['Automated ingestion and reconciliation','Source-linked lineage','Missing remains distinct from zero','Fail-closed validation and publishing','One-writer delivery and exact rollback'];
function Download({href,title,detail}:{href:string;title:string;detail:string}){return <a href={href}><span>↗</span><div><strong>{title}</strong><small>{detail}</small></div></a>}
export default function Home(){return <main>
 <section className="hero" id="top"><nav className="nav"><a className="wordmark" href="#top">PB<span>/</span>Platform</a><div className="nav-links"><a href="#outputs">Outputs</a><a href="#workflow">Workflow</a><a href="#technical">Technical</a><a href="#evidence">Evidence</a></div></nav><div className="hero-grid"><div><p className="eyebrow">Manufacturing intelligence case study</p><h1>Prepared reports. Faster review. Better operational context.</h1><p className="lede">A SharePoint-first platform that prepares consistent, source-linked shift, daily, and weekly reports for supervisors and managers to review and act on.</p><p className="role-line">Thomas Ryan · Forward Deployed Engineer Intern · May–August 2026</p><div className="hero-actions"><a className="button primary" href="#outputs">See how it is used</a></div></div><aside className="proof-panel"><p className="panel-label">The operational change</p><strong>Less assembly.<br/>More interpretation.</strong><p>Automation prepares the evidence. People review exceptions, add context, and retain decision authority.</p></aside></div></section>
 <section className="section output-section" id="outputs"><div className="compact-heading"><div><p className="eyebrow">Who uses what</p><h2>Three reporting products, three distinct jobs.</h2></div><p>Each output reduces preparation without hiding exceptions or replacing operational judgment.</p></div><div className="output-table"><div className="output-head"><span>Output</span><span>Automation prepares</span><span>People use it to</span></div>{outputs.map(o=><article key={o.name}><div><small>{o.user}</small><h3>{o.name}</h3></div><p>{o.prepare}</p><p>{o.use}</p></article>)}</div></section>
 <section className="dark-section" id="workflow"><div className="section"><div className="compact-heading light"><div><p className="eyebrow">Operational workflow</p><h2>One traceable path from input to action.</h2></div><p>The system prepares decision-support information; supervisors and managers decide what happens next.</p></div><div className="workflow-visual"><div><span>01</span><strong>Operational inputs</strong><small>Forms · SharePoint · files · machine events</small></div><b>→</b><div><span>02</span><strong>Prepare + validate</strong><small>Ingest · reconcile · link · test</small></div><b>→</b><div><span>03</span><strong>Reports + dashboard</strong><small>Shift · daily · weekly · live status</small></div><b>→</b><div className="red-step"><span>04</span><strong>Human review + action</strong><small>Interpret · prioritize · coordinate</small></div></div></div></section>
 <section className="section intelligence-section"><div className="compact-heading"><div><p className="eyebrow">Operational intelligence</p><h2>Three interfaces over governed reporting evidence.</h2></div><p>They retrieve, diagnose, or validate. None makes operational decisions or invents missing evidence.</p></div><div className="intelligence-grid"><article><span>CHATBOT</span><h3>Source-grounded retrieval</h3><p>Bounded report retrieval with structured responses, validated citations, and deterministic fallback.</p><strong>Estimated ~90% faster retrieval</strong><small>Modeled from 20–30 minutes to 1–2 minutes; scenario-dependent.</small></article><article><span>REPORT DOCTOR</span><h3>Read-only diagnostics</h3><p>Surfaces expected-output health, missing reports, exceptions, and settlement status without changing production state.</p><strong>Observe and investigate</strong><small>Diagnostics do not authorize repair or publication.</small></article><article><span>GOVERNED ORACLE</span><h3>Interpretation and validation</h3><p>Evaluates report evidence against explicit contracts and boundaries before downstream use.</p><strong>Evidence before confidence</strong><small>Missing or ambiguous evidence fails closed.</small></article></div></section>
 <section className="value-section" id="impact"><div className="section"><div className="compact-heading"><div><p className="eyebrow">Business value and assumptions</p><h2>Planning signals, not guaranteed outcomes.</h2></div><p>Each scenario is labeled and bounded so operational value is not confused with realized savings or autonomous decisions.</p></div><div className="impact-cards"><article><span>MODELED LABOR VALUE</span><strong>30 hours/week</strong><p>20 supervisor plus 10 manager hours of reporting effort addressed; about $52K annual labor value.</p></article><article><span>ESTIMATED RETRIEVAL</span><strong>~90% faster</strong><p>Modeled reduction from 20–30 minutes to 1–2 minutes for source-grounded report retrieval.</p></article><article className="secondary-impact"><span>MODELED UPPER-BOUND OPPORTUNITY</span><strong>Up to 227.5K widgets</strong><p>Approximately $205K annual contribution-margin opportunity under documented event, response-time, throughput, and margin assumptions.</p></article></div><details><summary>Impact methodology and boundaries</summary><p>Labor: 30 hours/week × 52 weeks with documented role-rate assumptions. Retrieval: representative 20–30 minute search reduced to 1–2 minutes. Downtime scenario: 5-minute response improvement × 1,000 widgets/hour/machine × 52.5 events/week × 52 weeks × $0.90/widget. These are planning models, not booked savings, realized margin, or guaranteed production.</p></details></div></section>
 <section className="architecture-section" id="technical"><div className="section architecture-grid"><div><p className="eyebrow">Technical foundation</p><h2>Simple to consume because the controls are explicit.</h2><ul>{controls.map(x=><li key={x}>{x}</li>)}</ul></div><div className="architecture-visual"><div><span>INPUTS</span><strong>SharePoint · Forms<br/>5 flows · machine events</strong></div><i>↓</i><div><span>REPORTING CORE</span><strong>Python · PostgreSQL<br/>8 source-linked tables</strong></div><i>↓</i><div><span>DELIVERY + INTELLIGENCE</span><strong>Workbooks · API · SPFx<br/>chatbot · doctor · oracle</strong></div><aside>Contracts · lineage · validation · readback · recovery · rollback</aside></div></div></section>
 <section className="preview-section" id="evidence"><div className="section"><div className="compact-heading"><div><p className="eyebrow">Explore the evidence</p><h2>Each artifact adds one distinct layer.</h2></div><p>The public package is synthetic and sanitized. Exact operating dependencies remain in the private successor handoff.</p></div><div className="preview-grid"><figure><Image src="/synthetic-report-summary.png" width={2172} height={1097} alt="Synthetic reporting workbook summary"/><figcaption><strong>Synthetic workbook</strong><span>Inspectable operational, intelligence, and recovery evidence.</span><a href="/synthetic-reliability-report.xlsx">Download Excel →</a></figcaption></figure><div className="artifact-stack"><Download href="/Thomas-Ryan-PepperBall-End-to-End-Case-Study.pdf" title="Technical case study" detail="Components, contracts, reliability, and impact methodology · PDF"/><Download href="https://github.com/tonnyryam/pepperball-reporting-platform-case-study" title="GitHub repository" detail="Implementation and public documentation"/><div className="share-links"><span>Share this case study</span><a href="/Thomas-Ryan-PepperBall-Case-Study.pdf">One-page PDF</a><a href="/Thomas-Ryan-PepperBall-Platform-Case-Study.pptx">Presentation deck</a></div></div></div></div></section>
 <footer><span>Thomas Ryan · Manufacturing reporting platform</span><p>Decision support—not autonomous decisions or guaranteed outcomes.</p></footer>
 </main>}
