"use client";
import Image from "next/image";
import { useEffect, useState } from "react";

const outputs = [
  { name: "Shift Drafts", user: "Supervisors", prepare: "Collection, reconciliation, organization, and spreadsheet preparation.", use: "Review exceptions, add operational context, and finalize shift reports." },
  { name: "Daily Production Reports", user: "Managers", prepare: "Production, molding, labor, quality, plan attainment, and downtime.", use: "Investigate constraints and prioritize staffing, planning, maintenance, or coordination." },
  { name: "Weekly Production + Downtime", user: "Managers and teams", prepare: "Comparable performance and downtime evidence across reporting periods.", use: "Identify trends, recurring issues, and priorities for planning, reviews, and handoffs." },
];
const controls = ["Automated ingestion and reconciliation", "Source-linked lineage", "Missing remains distinct from zero", "Fail-closed validation and publishing", "One-writer delivery and exact rollback"];
const navItems = [["outputs", "Reports"], ["workflow", "Workflow"], ["technical", "System"], ["depth", "Evidence"]];
const assistantModes = [
  { label: "Find", title: "Find cited information", text: "Locate exact-period reporting evidence with validated citations and deterministic fallback." },
  { label: "Diagnose", title: "Diagnose report problems", text: "Explain missing, delayed, or unsettled outputs through read-only expected-output and exception state." },
  { label: "Validate", title: "Validate evidence", text: "Check identity, lineage, state, and semantics—and refuse stale, missing, or ambiguous evidence." },
];

export default function Home() {
  const [active, setActive] = useState("outputs");
  const [progress, setProgress] = useState(0);
  const [assistantMode, setAssistantMode] = useState(0);
  const [previewOpen, setPreviewOpen] = useState(false);

  useEffect(() => {
    const updateProgress = () => { const max = document.documentElement.scrollHeight - innerHeight; setProgress(max > 0 ? Math.min(100, (scrollY / max) * 100) : 0); };
    updateProgress(); addEventListener("scroll", updateProgress, { passive: true });
    const sections = navItems.map(([id]) => document.getElementById(id)).filter(Boolean) as HTMLElement[];
    const sectionObserver = new IntersectionObserver(entries => { const visible = entries.filter(entry => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]; if (visible) setActive(visible.target.id); }, { rootMargin: "-20% 0px -55%", threshold: [0.1, 0.35, 0.65] });
    sections.forEach(section => sectionObserver.observe(section));
    const revealObserver = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add("in-view"); revealObserver.unobserve(entry.target); } }), { threshold: 0.16 });
    document.querySelectorAll("[data-reveal]").forEach(element => revealObserver.observe(element));
    const hashTarget = location.hash ? document.querySelector(location.hash) : null; if (hashTarget instanceof HTMLDetailsElement) hashTarget.open = true;
    return () => { removeEventListener("scroll", updateProgress); sectionObserver.disconnect(); revealObserver.disconnect(); };
  }, []);

  useEffect(() => {
    if (!previewOpen) return;
    const close = (event: KeyboardEvent) => { if (event.key === "Escape") setPreviewOpen(false); };
    document.body.style.overflow = "hidden";
    addEventListener("keydown", close);
    return () => { document.body.style.overflow = ""; removeEventListener("keydown", close); };
  }, [previewOpen]);

  const handleDetail = (event: React.SyntheticEvent<HTMLDetailsElement>, id: string) => {
    const current = event.currentTarget; if (!current.open) return;
    document.querySelectorAll<HTMLDetailsElement>(".depth-list details").forEach(detail => { if (detail !== current) detail.open = false; });
    history.replaceState(null, "", `#${id}`);
  };

  return <main>
    <div className="page-progress" aria-hidden="true"><span style={{ width: `${progress}%` }} /></div>
    <div className="sticky-shell"><nav className="nav" aria-label="Primary navigation"><a className="wordmark" href="#top">PB<span>/</span>Platform</a><div className="nav-links">{navItems.map(([id, label]) => <a key={id} className={active === id ? "active" : ""} href={`#${id}`}>{label}</a>)}</div></nav></div>
    <section className="hero" id="top"><div className="hero-grid"><div><p className="eyebrow hero-enter d1">Manufacturing Reporting Platform</p><h1 className="hero-enter d2">Prepared reports. Faster review. Better operational context.</h1><p className="lede hero-enter d3">A SharePoint-first platform that prepares consistent, source-linked shift, daily, and weekly reports for supervisors and managers to review and act on.</p><p className="role-line hero-enter d3">Thomas Ryan · Forward Deployed Engineer Intern · May-August 2026</p><div className="hero-actions hero-enter d4"><a className="button primary" href="#outputs">See how it is used</a></div></div><aside className="proof-panel hero-enter d4"><p className="panel-label">The operational change</p><strong>Less assembly.<br/>More interpretation.</strong><p>Automation prepares the evidence. People review exceptions, add context, and retain decision authority.</p></aside></div></section>

    <section className="section output-section" id="outputs" data-reveal><div className="compact-heading"><div><p className="eyebrow">Reports</p><h2>Who uses each report?</h2></div><p>Each reduces preparation without hiding exceptions or replacing operational judgment.</p></div><div className="output-table"><div className="output-head"><span>Report</span><span>What automation prepares</span><span>What people do</span></div>{outputs.map(o => <article key={o.name}><div><small>{o.user}</small><h3>{o.name}</h3></div><p>{o.prepare}</p><p>{o.use}</p></article>)}</div></section>

    <section className="dark-section" id="workflow" data-reveal><div className="section"><div className="compact-heading light"><div><p className="eyebrow">Workflow</p><h2>How does reporting lead to action?</h2></div><p>The platform prepares reports; supervisors and managers review exceptions, add context, and decide what happens next.</p></div><div className="workflow-visual" aria-label="Human reporting workflow"><div><span>01</span><strong>Collect inputs</strong><small>People record production activity</small></div><b aria-hidden="true">→</b><div><span>02</span><strong>Prepare reports</strong><small>Automation assembles a starting point</small></div><b aria-hidden="true">→</b><div><span>03</span><strong>Review exceptions</strong><small>People verify and add context</small></div><b aria-hidden="true">→</b><div className="red-step"><span>04</span><strong>Take action</strong><small>Interpret · prioritize · coordinate</small></div></div><p className="boundary-note">A sixth flow routes each newly published daily, weekly, or downtime report to its configured group with an attached snapshot when size permits and a link to the live SharePoint version.</p></div></section>

    <section className="section intelligence-section" data-reveal><div className="compact-heading"><div><p className="eyebrow">Reporting Assistant</p><h2>How does the reporting assistant help?</h2></div><p>One read-only assistant helps people find, diagnose, and validate reporting evidence.</p></div><article className="assistant-card"><div className="assistant-tabs" role="tablist" aria-label="Reporting Assistant capabilities">{assistantModes.map((mode, index) => <button key={mode.label} type="button" role="tab" aria-selected={assistantMode === index} onClick={() => setAssistantMode(index)}>{mode.label}</button>)}</div><div className="assistant-answer" role="tabpanel" aria-live="polite"><span>CONTROLLED CAPABILITY</span><h3>{assistantModes[assistantMode].title}</h3><p>{assistantModes[assistantMode].text}</p></div><p className="assistant-boundary">Read-only decision support—no report changes, publication authority, or operational decisions.</p></article></section>

    <section className="architecture-section" id="technical" data-reveal><div className="section architecture-grid"><div><p className="eyebrow">System</p><h2>How is the platform built and controlled?</h2><ul>{controls.map(x => <li key={x}>{x}</li>)}</ul></div><div className="architecture-visual" role="img" aria-label="Architecture from data intake through the reporting system to reports and assistant"><div tabIndex={0}><span>DATA INTAKE</span><strong>SharePoint · Forms<br/>6 flows · machine events</strong></div><i aria-hidden="true">↓</i><div tabIndex={0}><span>REPORTING SYSTEM</span><strong>Python · PostgreSQL<br/>8 source-linked tables</strong></div><i aria-hidden="true">↓</i><div tabIndex={0}><span>REPORTS + ASSISTANT</span><strong>Workbooks · API · SPFx<br/>Reporting Assistant</strong></div><aside>Contracts · lineage · validation · readback · recovery · rollback</aside></div></div></section>

    <section className="depth-section" id="depth" data-reveal><div className="section"><div className="depth-heading"><div><p className="eyebrow">Evidence</p><h2>Explore the evidence.</h2></div><a className="print-link" href="/Thomas-Ryan-PepperBall-Case-Study.pdf">Print/offline overview ↗</a></div><div className="depth-list">
      <details id="inspect-report" onToggle={event => handleDetail(event, "inspect-report")}><summary><span>01</span><div><strong>Inspect a sample report</strong><small>Lineage, calculations, missingness, and exceptions</small></div></summary><div className="depth-content report-depth"><figure><button className="preview-button" type="button" onClick={() => setPreviewOpen(true)} aria-label="Enlarge the synthetic report preview"><Image src="/synthetic-report-summary.png" width={2172} height={1097} alt="Synthetic reporting workbook summary showing operational measures and evidence status"/><span>Enlarge ↗</span></button><figcaption>Synthetic data only; structured to demonstrate inspection and traceability.</figcaption></figure><div><h3>Follow evidence, not a screenshot.</h3><ul><li>Trace values from source category to prepared output.</li><li>Distinguish absent evidence from a measured zero.</li><li>Review exceptions and recovery state without production access.</li><li>Inspect Reporting Assistant boundaries and impact calculations.</li></ul><a className="depth-action" href="/synthetic-reliability-report.xlsx">Download the evidence workbook ↗</a></div></div></details>
      <details id="engineering-depth" onToggle={event => handleDetail(event, "engineering-depth")}><summary><span>02</span><div><strong>Explore system architecture</strong><small>Contracts, state, validation, recovery, and tradeoffs</small></div></summary><div className="depth-content engineering-depth"><div><h3>Reliability is represented as explicit state.</h3><p>Report identity, expected-output state, material identity, source lineage, semantic certification, publication state, and readback settlement are tracked independently.</p><p>The public Reporting Assistant uses bounded chatbot retrieval, read-only report-doctor diagnostics, and governed-oracle validation as controlled internal subsystems.</p><div className="state-path" aria-label="Publication state path"><span>candidate</span><b>→</b><span>validated</span><b>→</b><span>published</span><b>→</b><span>read back</span><b>→</b><span>settled</span></div></div><div className="tradeoff-table"><h3>Selected design tradeoffs</h3><p><b>Fail closed:</b> slower settlement is preferred to publishing ambiguous evidence.</p><p><b>One writer:</b> serialized releases trade deployment concurrency for unambiguous ownership.</p><p><b>Bounded repair:</b> exact eligible evidence may recover; unsupported reconstruction is refused.</p><a className="depth-action" href="/Thomas-Ryan-PepperBall-End-to-End-Case-Study.pdf">Read the engineering reference ↗</a></div></div></details>
      <details id="impact-depth" onToggle={event => handleDetail(event, "impact-depth")}><summary><span>03</span><div><strong>Review impact evidence</strong><small>Observed conformance and qualified planning models</small></div></summary><div className="depth-content impact-depth"><article><span>REVIEWED REPORT CONFORMANCE</span><strong>About 75% → 100%</strong><p>Across approximately six months reviewed, about one in four legacy reports did not follow the required production-count schema; every reviewed system-generated output did.</p></article><article><span>MODELED LABOR VALUE</span><strong>30 hours/week · about $52K/year</strong><p>20 supervisor plus 10 manager hours per week × 52 weeks using documented role-rate assumptions.</p></article><article><span>ESTIMATED RETRIEVAL</span><strong>About 90% faster</strong><p>Representative 20-30 minute report search reduced to 1-2 minutes with bounded retrieval.</p></article><article><span>MODELED UPPER BOUND</span><strong>Up to 227.5K production units · about $205K</strong><p>5 minutes × 1,000 production units/hour/machine × 52.5 events/week × 52 weeks × $0.90/unit.</p></article><p className="boundary-note">The conformance result is limited to the reviewed sample. Planning scenarios are not booked savings, realized production, guaranteed margin, or autonomous outcomes.</p></div></details>
      <details id="implementation-evidence" onToggle={event => handleDetail(event, "implementation-evidence")}><summary><span>04</span><div><strong>Examine validation evidence</strong><small>Validation layers, release history, and sanitized source</small></div></summary><div className="depth-content evidence-depth"><div><h3>Representative validation layers</h3><ul><li>Source-derived conservation and reconciliation checks</li><li>Workbook structure, semantics, and normalized rendering</li><li>Exact SharePoint download/readback settlement</li><li>Immediate equivalent replay with no second write</li><li>Serialized promotion with exact rollback</li></ul></div><div><h3>Public implementation record</h3><p>The repository contains sanitized architecture, state-machine documentation, tests, release chronology, synthetic scenarios, and claim boundaries. Exact tenant, credential, and operating details remain private.</p><a className="depth-action" href="https://github.com/tonnyryam/pepperball-reporting-platform-case-study">Explore the GitHub repository ↗</a></div></div></details>
    </div></div></section>

    <footer><span>Thomas Ryan · Manufacturing reporting platform</span><nav aria-label="Contact links"><a href="https://www.linkedin.com/in/thomas-f-ryan/">LinkedIn</a><a href="mailto:tommyryan.sf415@gmail.com">Email</a></nav><p>People make decisions; the platform provides evidence.</p></footer>
    {previewOpen && <div className="preview-modal" role="dialog" aria-modal="true" aria-label="Synthetic report preview" onClick={() => setPreviewOpen(false)}><div onClick={event => event.stopPropagation()}><button type="button" onClick={() => setPreviewOpen(false)} aria-label="Close enlarged preview">Close ×</button><Image src="/synthetic-report-summary.png" width={2172} height={1097} alt="Enlarged synthetic reporting workbook summary showing operational measures and evidence status"/></div></div>}
  </main>;
}
