import Image from "next/image";

const outputs = [
  { name: "Shift Drafts", user: "Supervisors", prepare: "Collection, reconciliation, organization, and spreadsheet preparation.", use: "Review exceptions, add operational context, and finalize shift reports." },
  { name: "Daily Production Reports", user: "Managers", prepare: "Production, molding, labor, quality, plan attainment, and downtime.", use: "Investigate constraints and prioritize staffing, planning, maintenance, or coordination." },
  { name: "Weekly Production + Downtime", user: "Managers and teams", prepare: "Comparable performance and downtime evidence across reporting periods.", use: "Identify trends, recurring issues, and priorities for planning, reviews, and handoffs." },
];
const controls = ["Automated ingestion and reconciliation", "Source-linked lineage", "Missing remains distinct from zero", "Fail-closed validation and publishing", "One-writer delivery and exact rollback"];

export default function Home() {
  return <main>
    <section className="hero" id="top">
      <nav className="nav" aria-label="Primary navigation"><a className="wordmark" href="#top">PB<span>/</span>Platform</a><div className="nav-links"><a href="#outputs">Outputs</a><a href="#workflow">Workflow</a><a href="#technical">Technical</a><a href="#depth">Explore</a></div></nav>
      <div className="hero-grid"><div><p className="eyebrow">Manufacturing intelligence case study</p><h1>Prepared reports. Faster review. Better operational context.</h1><p className="lede">A SharePoint-first platform that prepares consistent, source-linked shift, daily, and weekly reports for supervisors and managers to review and act on.</p><p className="role-line">Thomas Ryan · Forward Deployed Engineer Intern · May-August 2026</p><div className="hero-actions"><a className="button primary" href="#outputs">See how it is used</a></div></div><aside className="proof-panel"><p className="panel-label">The operational change</p><strong>Less assembly.<br/>More interpretation.</strong><p>Automation prepares the evidence. People review exceptions, add context, and retain decision authority.</p></aside></div>
    </section>

    <section className="section output-section" id="outputs"><div className="compact-heading"><div><p className="eyebrow">Who uses what</p><h2>Three outputs, three distinct jobs.</h2></div><p>Each reduces preparation without hiding exceptions or replacing operational judgment.</p></div><div className="output-table"><div className="output-head"><span>Output</span><span>Automation prepares</span><span>People use it to</span></div>{outputs.map(o=><article key={o.name}><div><small>{o.user}</small><h3>{o.name}</h3></div><p>{o.prepare}</p><p>{o.use}</p></article>)}</div></section>

    <section className="dark-section" id="workflow"><div className="section"><div className="compact-heading light"><div><p className="eyebrow">Operational workflow</p><h2>One traceable path from input to action.</h2></div><p>The platform prepares decision-support information; supervisors and managers decide what happens next.</p></div><div className="workflow-visual" aria-label="Operational input to human action workflow"><div><span>01</span><strong>Operational inputs</strong><small>Forms · SharePoint · files · machine events</small></div><b aria-hidden="true">→</b><div><span>02</span><strong>Prepare + validate</strong><small>Ingest · reconcile · link · test</small></div><b aria-hidden="true">→</b><div><span>03</span><strong>Reports + dashboard</strong><small>Shift · daily · weekly · live status</small></div><b aria-hidden="true">→</b><div className="red-step"><span>04</span><strong>Human review + action</strong><small>Interpret · prioritize · coordinate</small></div></div></div></section>

    <section className="section intelligence-section"><div className="compact-heading"><div><p className="eyebrow">Operational intelligence</p><h2>Three bounded interfaces over governed evidence.</h2></div><p>They retrieve, diagnose, or validate. None makes operational decisions or invents missing evidence.</p></div><div className="intelligence-grid"><article><span>CHATBOT</span><h3>Retrieve</h3><p>Source-grounded report retrieval with structured responses, validated citations, and deterministic fallback.</p></article><article><span>REPORT DOCTOR</span><h3>Diagnose</h3><p>Read-only expected-output, exception, and settlement diagnostics without repair or publication authority.</p></article><article><span>GOVERNED ORACLE</span><h3>Validate</h3><p>Contract-, lineage-, identity-, state-, and semantics-bound interpretation that fails closed.</p></article></div></section>

    <section className="architecture-section" id="technical"><div className="section architecture-grid"><div><p className="eyebrow">Technical foundation</p><h2>Simple to consume because the controls are explicit.</h2><ul>{controls.map(x=><li key={x}>{x}</li>)}</ul></div><div className="architecture-visual" role="img" aria-label="Architecture from operational inputs through reporting core to delivery and intelligence"><div><span>INPUTS</span><strong>SharePoint · Forms<br/>5 flows · machine events</strong></div><i aria-hidden="true">↓</i><div><span>REPORTING CORE</span><strong>Python · PostgreSQL<br/>8 source-linked tables</strong></div><i aria-hidden="true">↓</i><div><span>DELIVERY + INTELLIGENCE</span><strong>Workbooks · API · SPFx<br/>chatbot · doctor · oracle</strong></div><aside>Contracts · lineage · validation · readback · recovery · rollback</aside></div></div></section>

    <section className="depth-section" id="depth"><div className="section">
      <div className="depth-heading"><div><p className="eyebrow">Choose what to inspect</p><h2>One story. Optional evidence and engineering depth.</h2></div><a className="print-link" href="/Thomas-Ryan-PepperBall-Case-Study.pdf">Print/offline overview ↗</a></div>
      <div className="depth-list">
        <details id="inspect-report"><summary><span>01</span><div><strong>Inspect a report</strong><small>Lineage, calculations, missingness, and exceptions</small></div></summary><div className="depth-content report-depth"><figure><Image src="/synthetic-report-summary.png" width={2172} height={1097} alt="Synthetic reporting workbook summary showing operational measures and evidence status"/><figcaption>Synthetic data only; structured to demonstrate inspection and traceability.</figcaption></figure><div><h3>Follow evidence, not a screenshot.</h3><ul><li>Trace values from source category to prepared output.</li><li>Distinguish absent evidence from a measured zero.</li><li>Review exceptions and recovery state without production access.</li><li>Inspect intelligence boundaries and impact calculations.</li></ul><a className="depth-action" href="/synthetic-reliability-report.xlsx">Download the evidence workbook ↗</a></div></div></details>

        <details id="engineering-depth"><summary><span>02</span><div><strong>Understand the engineering</strong><small>Contracts, state, validation, recovery, and tradeoffs</small></div></summary><div className="depth-content engineering-depth"><div><h3>Reliability is represented as explicit state.</h3><p>Report identity, expected-output state, material identity, source lineage, semantic certification, publication state, and readback settlement are tracked independently.</p><div className="state-path" aria-label="Publication state path"><span>candidate</span><b>→</b><span>validated</span><b>→</b><span>published</span><b>→</b><span>read back</span><b>→</b><span>settled</span></div></div><div className="tradeoff-table"><h3>Selected design tradeoffs</h3><p><b>Fail closed:</b> slower settlement is preferred to publishing ambiguous evidence.</p><p><b>One writer:</b> serialized releases trade deployment concurrency for unambiguous ownership.</p><p><b>Bounded repair:</b> exact eligible evidence may recover; unsupported reconstruction is refused.</p><a className="depth-action" href="/Thomas-Ryan-PepperBall-End-to-End-Case-Study.pdf">Read the engineering reference ↗</a></div></div></details>

        <details id="impact-depth"><summary><span>03</span><div><strong>Review impact assumptions</strong><small>Transparent planning models, qualifications, and limits</small></div></summary><div className="depth-content impact-depth"><article><span>MODELED LABOR VALUE</span><strong>30 hours/week · about $52K/year</strong><p>20 supervisor plus 10 manager hours per week × 52 weeks using documented role-rate assumptions.</p></article><article><span>ESTIMATED RETRIEVAL</span><strong>About 90% faster</strong><p>Representative 20-30 minute report search reduced to 1-2 minutes with bounded retrieval.</p></article><article><span>MODELED UPPER BOUND</span><strong>Up to 227.5K widgets · about $205K</strong><p>5 minutes × 1,000 widgets/hour/machine × 52.5 events/week × 52 weeks × $0.90/widget.</p></article><p className="boundary-note">Planning scenarios only - not booked savings, realized production, guaranteed margin, or autonomous outcomes.</p></div></details>

        <details id="implementation-evidence"><summary><span>04</span><div><strong>See implementation evidence</strong><small>Validation layers, release history, and sanitized source</small></div></summary><div className="depth-content evidence-depth"><div><h3>Representative validation layers</h3><ul><li>Source-derived conservation and reconciliation checks</li><li>Workbook structure, semantics, and normalized rendering</li><li>Exact SharePoint download/readback settlement</li><li>Immediate equivalent replay with no second write</li><li>Serialized promotion with exact rollback</li></ul></div><div><h3>Public implementation record</h3><p>The repository contains sanitized architecture, state-machine documentation, tests, release chronology, synthetic scenarios, and claim boundaries. Exact tenant, credential, and operating details remain private.</p><a className="depth-action" href="https://github.com/tonnyryam/pepperball-reporting-platform-case-study">Explore the GitHub repository ↗</a></div></div></details>
      </div>
    </div></section>

    <footer><span>Thomas Ryan · Manufacturing reporting platform</span><nav aria-label="Contact links"><a href="https://www.linkedin.com/in/thomas-f-ryan/">LinkedIn</a><a href="mailto:tommyryan.sf415@gmail.com">Email</a></nav><p>Decision support - not autonomous decisions or guaranteed outcomes.</p></footer>
  </main>;
}
