from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, KeepTogether

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/"public"
RED=colors.HexColor("#D52B1E"); INK=colors.HexColor("#171717"); GREY=colors.HexColor("#626262"); PALE=colors.HexColor("#FBE8E6"); PAPER=colors.HexColor("#F4F4F2"); LINE=colors.HexColor("#D0D0CD")
styles=getSampleStyleSheet()
styles.add(ParagraphStyle(name="TitleX",parent=styles["Title"],fontSize=27,leading=30,textColor=INK,spaceAfter=16))
styles.add(ParagraphStyle(name="H1X",parent=styles["Heading1"],fontSize=18,leading=22,textColor=RED,spaceBefore=14,spaceAfter=8))
styles.add(ParagraphStyle(name="H2X",parent=styles["Heading2"],fontSize=13,leading=16,textColor=INK,spaceBefore=10,spaceAfter=5))
styles.add(ParagraphStyle(name="BodyX",parent=styles["BodyText"],fontSize=9.4,leading=13.2,textColor=GREY,spaceAfter=7))
styles.add(ParagraphStyle(name="SmallX",parent=styles["BodyText"],fontSize=7.5,leading=10,textColor=GREY))
styles.add(ParagraphStyle(name="CellX",parent=styles["BodyText"],fontSize=7.2,leading=9,textColor=GREY))

def footer(c,d):
 c.saveState(); c.setFont("Helvetica",8); c.setFillColor(GREY); c.drawString(inch,.45*inch,"THOMAS RYAN  |  MANUFACTURING REPORTING PLATFORM"); c.drawRightString(7.5*inch,.45*inch,str(d.page)); c.restoreState()
def p(t,s="BodyX"): return Paragraph(t,styles[s])
def table(rows,widths=None,header=True):
 data=[[p(str(x),"CellX") for x in row] for row in rows]
 t=Table(data,colWidths=widths,repeatRows=1 if header else 0)
 rules=[("GRID",(0,0),(-1,-1),.45,LINE),("VALIGN",(0,0),(-1,-1),"TOP"),("LEFTPADDING",(0,0),(-1,-1),6),("RIGHTPADDING",(0,0),(-1,-1),6),("TOPPADDING",(0,0),(-1,-1),6),("BOTTOMPADDING",(0,0),(-1,-1),6)]
 if header: rules += [("BACKGROUND",(0,0),(-1,0),INK),("TEXTCOLOR",(0,0),(-1,0),colors.white),("FONTNAME",(0,0),(-1,0),"Helvetica-Bold")]
 t.setStyle(TableStyle(rules)); return t
def doc(path): return SimpleDocTemplate(str(path),pagesize=letter,rightMargin=.75*inch,leftMargin=.75*inch,topMargin=.65*inch,bottomMargin=.7*inch,title="PepperBall Reporting Platform Case Study",author="Thomas Ryan")

def build_one_page():
 story=[Spacer(1,.45*inch),p("Prepared reports. Faster review.<br/>Better operational context.","TitleX"),p("Printable executive overview of a SharePoint-first manufacturing intelligence platform."),p("How people use the outputs","H1X"),p("<b>Shift Drafts:</b> supervisors receive a prepared starting point, review exceptions, add context, and finalize. <b>Daily Production:</b> managers investigate production, molding, labor, quality, plan attainment, and downtime. <b>Weekly Production + Downtime:</b> teams identify trends, recurring constraints, and planning priorities.")]
 story += [table([["INPUT","PREPARE + VALIDATE","OUTPUT","HUMAN REVIEW + ACTION"],["Forms, SharePoint, files, machine events","Ingest, reconcile, link sources, test","Shift, daily, weekly, dashboard","Interpret context, prioritize, coordinate"]],[1.55*inch]*4)]
 story += [p("Bounded intelligence","H1X"),p("<b>Chatbot</b> retrieves governed evidence with citations and deterministic fallback. <b>Report doctor</b> observes expected-output and exception state without mutation. <b>Governed oracle</b> validates interpretation against contracts and fails closed."),p("Qualified planning signals","H1X"),p("<b>Modeled:</b> 30 reporting hours/week addressed and about $52K annual labor value. <b>Estimated:</b> about 90% faster retrieval in the documented 20-30 minute to 1-2 minute scenario. <b>Upper-bound model:</b> up to 227.5K widgets and about $205K contribution-margin opportunity under documented assumptions."),p("Decision support only - not autonomous decisions, booked savings, realized production, or guaranteed margin.","SmallX")]
 doc(OUT/"Thomas-Ryan-PepperBall-Case-Study.pdf").build(story,onFirstPage=footer,onLaterPages=footer)

def build_long():
 s=[Spacer(1,.35*inch),p("Engineering reference:<br/>governed manufacturing reporting","TitleX"),p("A sanitized technical case study covering architecture, contracts, state, validation, failure handling, tradeoffs, and impact methodology."),p("Reading guide","H1X")]
 s += [table([["QUESTION","SECTION"],["How is the platform used?","1. Operational contract"],["What is implemented?","2. Architecture and data model"],["Why is delivery reliable?","3. State, validation, and recovery"],["How is evidence tested?","4. Verification matrix"],["What do the intelligence interfaces do?","5. Bounded intelligence"],["How are impact figures qualified?","6. Impact methodology"]],[3.1*inch,3.1*inch])]
 s += [p("Public/private boundary","H1X"),p("This reference uses synthetic data and sanitized topology. Tenant identifiers, employee data, production URLs, credentials, exact commands, permissions, and successor procedures remain in the private handoff."),PageBreak()]

 s += [p("1. Operational contract","TitleX"),p("The platform prepares decision-support evidence; people retain operational authority."),table([["OUTPUT","PRIMARY USER","PLATFORM RESPONSIBILITY","HUMAN RESPONSIBILITY"],["Shift Draft","Supervisor","Collect, reconcile, organize, prepare spreadsheet","Review exceptions, add context, finalize"],["Daily Production","Manager","Combine production, molding, labor, quality, plan, downtime","Investigate constraints and prioritize follow-up"],["Weekly Production","Managers / teams","Create comparable period and trend views","Plan capacity and labor; prioritize improvement"],["Weekly Downtime","Managers / maintenance","Classify recurring and isolated downtime evidence","Set maintenance and coordination priorities"]],[1.2*inch,1.05*inch,2.05*inch,2.05*inch]),p("Decision boundary","H1X"),p("Automation may prepare, classify, validate, refuse, and report state. It does not autonomously change staffing, production plans, maintenance priorities, or cross-department actions."),PageBreak()]

 s += [p("2. Architecture and data model","TitleX"),table([["LAYER","COMPONENTS","RESPONSIBILITY"],["Intake","SharePoint, Forms, five Power Automate flows, machine events","Retain operational inputs and trigger bounded collection"],["Reporting core","Python ingestion/reconciliation, PostgreSQL","Normalize evidence and maintain source-linked serving state"],["Outputs","Workbooks, SharePoint libraries, API/SPFx dashboard","Expose prepared shift, daily, weekly, and live-status views"],["Intelligence","Chatbot, report doctor, governed oracle","Retrieve, diagnose, or validate without acquiring decision authority"]],[1.1*inch,2.15*inch,3.0*inch]),p("Eight source-linked reporting tables","H1X"),p("The serving model separates hourly production, quality, labor, molding, machine notes/events, final reports, report state, and lineage/settlement evidence. Separation prevents an output-friendly aggregate from erasing source identity or missingness."),table([["CONTRACT","WHY EXPLICIT"],["Report identity","Prevents one period/family from settling another"],["Material identity","Distinguishes governed fact changes from capture-only metadata"],["Source lineage","Connects each prepared value to qualified evidence"],["Semantic certification","Tests meaning rather than file appearance alone"],["Publication/readback state","Separates accepted write from verified remote content"]],[1.65*inch,4.65*inch]),PageBreak()]

 state=table([["CANDIDATE","VALIDATED","PUBLISHED","READ BACK","SETTLED"]],[1.26*inch]*5,header=False); state.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),PALE),("TEXTCOLOR",(0,0),(-1,-1),RED),("FONTNAME",(0,0),(-1,-1),"Helvetica-Bold"),("ALIGN",(0,0),(-1,-1),"CENTER")]))
 s += [p("3. State, validation, and recovery","TitleX"),state,Spacer(1,.1*inch),p("State advances only when the evidence required for that transition exists. Missing evidence remains missing; an observed zero remains zero. A successful request is not equivalent to a verified remote artifact."),p("Failure scenarios","H1X"),table([["SCENARIO","CLASSIFICATION","SAFE BEHAVIOR","AUTHORITY"],["Required source absent","pending_source","Retain expected output; do not publish","No write"],["Equivalent replay","exact_no_op","Conserve material identity and remote version","No write"],["Write accepted; response lost","readback_pending","GET exact item; never repeat PUT","GET only"],["Contract or lineage drift","contract_refusal","Stop interpretation/publication","No write"],["Eligible late source","bounded_recovery","Advance same output identity once after validation","One qualified write"]],[1.35*inch,1.25*inch,2.55*inch,1.15*inch]),p("Release and rollback","H1X"),p("One-writer releases serialize ownership and prevent overlapping publication. Promotion is guarded by output-suppressed/current-data checks. Exact rollback restores the last known-good immutable revision rather than reconstructing a deployment from mutable state."),PageBreak()]

 s += [p("4. Verification matrix","TitleX"),table([["LAYER","REPRESENTATIVE CHECK","FAILURE PREVENTED"],["Source facts","Conservation and reconciliation against qualified inputs","Dropped or duplicated evidence"],["Workbook package","Visible sheets, formulas, structure, stored values","Client-dependent or malformed output"],["Semantics","Missing-versus-zero and family-specific rules","Meaning drift"],["Normalized rendering","Stable content independent of packaging noise","False changes from metadata"],["Remote readback","Exact item, version, ETag, content/material hash","Accepted-write ambiguity"],["Replay","Immediate equivalent cycle makes zero second PUT","Duplicate versions"],["Release","Serialized handoff, readiness guard, exact rollback","Concurrent writers / unsafe promotion"]],[1.25*inch,2.8*inch,2.35*inch]),p("Claim discipline","H1X"),p("Validation coverage proves the tested invariants and scenarios. It is not presented as blanket accuracy. Public evidence is sanitized; production-specific receipts and exact successor tests remain private."),p("Selected tradeoffs","H1X"),table([["CHOICE","BENEFIT","COST"],["Fail closed","No silent advancement on ambiguity","Some reports settle later"],["One writer","Clear ownership and recovery semantics","Serialized promotion"],["Same-item advancement","Stable operational identity and links","Requires strict replay/material checks"],["Bounded repair","Recovers only evidence-supported cases","Some historical cases remain terminal holds"]],[1.35*inch,2.5*inch,2.55*inch]),PageBreak()]

 s += [p("5. Bounded intelligence","TitleX"),table([["INTERFACE","PURPOSE","BOUNDARY","REPRESENTATIVE REFUSAL"],["Chatbot","Source-grounded report retrieval","Structured response, validated citation, deterministic fallback","Unsupported question or missing source"],["Report doctor","Expected-output, exception, and settlement diagnostics","Read-only; no repair or publication authority","Non-admin or unavailable exact-period evidence"],["Governed oracle","Contract-bound interpretation and validation","Identity, lineage, state, semantics must agree","Stale, missing, or ambiguous evidence"]],[1.15*inch,1.75*inch,2.1*inch,1.45*inch]),p("Why three interfaces","H1X"),p("Retrieval, diagnosis, and validation have different authority and failure modes. Keeping them separate makes refusal behavior understandable and prevents a convenient question-answering surface from silently becoming an operator, publisher, or universal truth source."),p("Human control","H1X"),p("The interfaces can make evidence easier to locate and inspect. Supervisors and managers still interpret context and choose operational action."),PageBreak()]

 s += [p("6. Impact methodology","TitleX"),table([["MODEL","ASSUMPTIONS","CALCULATION","QUALIFICATION"],["Labor","20 supervisor + 10 manager hours/week; 52 weeks; documented role-rate assumptions","30 hours/week; about $52K/year","Modeled value, not booked savings"],["Retrieval","Representative 20-30 minute search; 1-2 minute bounded retrieval","About 90% reduction","Estimated, scenario-dependent"],["Downtime","5-minute response improvement; 1,000 widgets/hour/machine; 52.5 events/week; 52 weeks; $0.90/widget","Up to 227,500 widgets; about $205K contribution margin","Upper-bound opportunity, not realized production or margin"]],[1.05*inch,2.35*inch,1.75*inch,1.35*inch]),p("Limitations","H1X"),p("The models depend on representative time studies, event frequency, throughput, response improvement, role rates, and contribution margin. They are useful for prioritization and sensitivity analysis, not guarantees. The synthetic workbook exposes editable inputs and formula-driven outputs so assumptions can be challenged directly."),p("Implementation references","H1X"),p("The public repository contains sanitized architecture, state-machine documentation, tests, synthetic scenarios, release chronology, and claim boundaries. The private successor package contains exact dependencies, permissions, operating procedures, rollback, credentials transfer, and acceptance checks.")]
 doc(OUT/"Thomas-Ryan-PepperBall-End-to-End-Case-Study.pdf").build(s,onFirstPage=footer,onLaterPages=footer)

build_one_page(); build_long()
